/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiStripeVerifyRouteImport } from './routes/api/stripe/verify'
import { Route as ApiStripeCreateCheckoutRouteImport } from './routes/api/stripe/create-checkout'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron/reminders'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeVerifyRoute = ApiStripeVerifyRouteImport.update({
  id: '/api/stripe/verify',
  path: '/api/stripe/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCreateCheckoutRoute = ApiStripeCreateCheckoutRouteImport.update({
  id: '/api/stripe/create-checkout',
  path: '/api/stripe/create-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/confirmation': typeof ConfirmationRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/stripe/create-checkout': typeof ApiStripeCreateCheckoutRoute
  '/api/stripe/verify': typeof ApiStripeVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/confirmation': typeof ConfirmationRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/stripe/create-checkout': typeof ApiStripeCreateCheckoutRoute
  '/api/stripe/verify': typeof ApiStripeVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/confirmation': typeof ConfirmationRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/stripe/create-checkout': typeof ApiStripeCreateCheckoutRoute
  '/api/stripe/verify': typeof ApiStripeVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/confirmation'
    | '/consent'
    | '/dashboard'
    | '/login'
    | '/payment'
    | '/profile'
    | '/reset-password'
    | '/services'
    | '/unsubscribe'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/api/cron/reminders'
    | '/api/stripe/create-checkout'
    | '/api/stripe/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/confirmation'
    | '/consent'
    | '/dashboard'
    | '/login'
    | '/payment'
    | '/profile'
    | '/reset-password'
    | '/services'
    | '/unsubscribe'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/api/cron/reminders'
    | '/api/stripe/create-checkout'
    | '/api/stripe/verify'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/confirmation'
    | '/consent'
    | '/dashboard'
    | '/login'
    | '/payment'
    | '/profile'
    | '/reset-password'
    | '/services'
    | '/unsubscribe'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/api/cron/reminders'
    | '/api/stripe/create-checkout'
    | '/api/stripe/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ConsentRoute: typeof ConsentRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  ApiStripeCreateCheckoutRoute: typeof ApiStripeCreateCheckoutRoute
  ApiStripeVerifyRoute: typeof ApiStripeVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/verify': {
      id: '/api/stripe/verify'
      path: '/api/stripe/verify'
      fullPath: '/api/stripe/verify'
      preLoaderRoute: typeof ApiStripeVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/create-checkout': {
      id: '/api/stripe/create-checkout'
      path: '/api/stripe/create-checkout'
      fullPath: '/api/stripe/create-checkout'
      preLoaderRoute: typeof ApiStripeCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  ConfirmationRoute: ConfirmationRoute,
  ConsentRoute: ConsentRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  ApiStripeCreateCheckoutRoute: ApiStripeCreateCheckoutRoute,
  ApiStripeVerifyRoute: ApiStripeVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
